version: '3'
services:
  api:
    build: ./linkStorageAPI

    restart: always
    
    ports:
      - "8000:8000"

    depends_on:
     - db

  db:
    image: mysql

    restart: always

    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - "3306:3306"
